//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import "errors"

type EnumMood string

const (
	EnumMood_Happy   EnumMood = "happy"
	EnumMood_Sad     EnumMood = "sad"
	EnumMood_Neutral EnumMood = "neutral"
)

func (e *EnumMood) Scan(value interface{}) error {
	var enumValue string
	switch val := value.(type) {
	case string:
		enumValue = val
	case []byte:
		enumValue = string(val)
	default:
		return errors.New("jet: Invalid scan value for AllTypesEnum enum. Enum value has to be of type string or []byte")
	}

	switch enumValue {
	case "happy":
		*e = EnumMood_Happy
	case "sad":
		*e = EnumMood_Sad
	case "neutral":
		*e = EnumMood_Neutral
	default:
		return errors.New("jet: Invalid scan value '" + enumValue + "' for EnumMood enum")
	}

	return nil
}

func (e EnumMood) String() string {
	return string(e)
}
