//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var EnumMood = &struct {
	Happy   postgres.StringExpression
	Sad     postgres.StringExpression
	Neutral postgres.StringExpression
}{
	Happy:   postgres.NewEnumValue("happy"),
	Sad:     postgres.NewEnumValue("sad"),
	Neutral: postgres.NewEnumValue("neutral"),
}
